const FALLBACK=window.__FALLBACK_DATA__;
const DEFAULT_FEED='https://docs.google.com/spreadsheets/d/e/2PACX-1vQBDuJV6VmbwRheiQP9XwAXWlR89IUORKFRSwDk9U2AbR_tVcPTJKuGTCLjeR0F__jNy1zlL68jQQn_/pub?gid=2110283304&single=true&output=csv';
const KTX='quantPrivateTransactionsV3',KPRICE='quantPrivatePricesV3',KFEED='quantFeedUrlV3',KMARKET='quantMarketCacheV3',KPRIVATEURL='quantPrivateSyncUrlV3',KPRIVTOKEN='quantPrivateSyncTokenV3';
let market=FALLBACK,txs=[],manualPrices={},privatePositions=[],pendingPrivate={};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),num=x=>(x===null||x===undefined||String(x).trim()==='')?null:(Number.isFinite(Number(x))?Number(x):null),money=x=>num(x)===null?'—':'Rp'+Math.round(Number(x)).toLocaleString('id-ID'),pct=x=>num(x)===null?'N/A':(Number(x)>0?'+':'')+Number(x).toFixed(2)+'%';
function parseCSV(t){let R=[],r=[],c='',q=false;for(let i=0;i<t.length;i++){let x=t[i],n=t[i+1];if(x=='"'){if(q&&n=='"'){c+='"';i++}else q=!q}else if(x==','&&!q){r.push(c);c=''}else if((x=='\n'||x=='\r')&&!q){if(x=='\r'&&n=='\n')i++;r.push(c);c='';if(r.some(v=>v!==''))R.push(r);r=[]}else c+=x}if(c!==''||r.length){r.push(c);R.push(r)}return R}
function conv(v,t){if(t==='number'){let n=Number(v);return Number.isFinite(n)?n:v}if(t==='boolean')return String(v).toLowerCase()==='true';return v}
function applyFeed(csv){let rows=parseCSV(csv),h=rows[0]||[],ix=k=>h.indexOf(k),d=JSON.parse(JSON.stringify(FALLBACK));d.decisions={};if(['record_type','record_id','field','value','value_type','as_of_date'].some(k=>ix(k)<0))throw Error('Wrong feed');let L={};rows.slice(1).forEach(r=>{let type=r[ix('record_type')]||'',id=r[ix('record_id')]||'',field=r[ix('field')]||'',date=r[ix('as_of_date')]||'',key=type+'|'+id+'|'+field;if(field&&(!L[key]||date>=L[key].date))L[key]={type,id,field,date,value:conv(r[ix('value')],r[ix('value_type')])}});Object.values(L).forEach(o=>{if(o.type==='meta')d.meta[o.field]=o.value;else if(o.type==='regime'){if(['label','risk','takeaway'].includes(o.field))d.regime[o.field]=o.value;let m={brent:'Brent',us10y:'US 10Y',fedOdds:'Fed hike odds'};if(m[o.field]){let c=d.regime.chips.find(x=>x.label===m[o.field]);if(c)c.value=o.value}}else if(o.type==='signal'){let s=d.signals.find(x=>x.id===o.id);if(!s){s={id:o.id};d.signals.push(s)}s[o.field]=o.field==='thesis'?String(o.value).split('|'):o.value}else if(o.type==='decision'){d.decisions[o.id]=d.decisions[o.id]||{};d.decisions[o.id][o.field]=o.value}else if(o.type==='watch'&&o.field==='summary'){let a=String(o.value).split('|'),w=d.watchlist.find(x=>x.id===o.id),nw={id:o.id,instrument:a[0]||o.id,action:'WAIT',reference:a[1]||'—',trigger:a[2]||'—',target:a[3]||'—',stop:a[4]||'—',note:a[5]||''};w?Object.assign(w,nw):d.watchlist.push(nw)}else if(o.type==='score')d.scorecard[o.field]=o.value;else if(o.type==='history'&&o.field==='summary')d.history.push({date:o.date,text:String(o.value)})});return d}
function setSync(t,c=''){$('syncText').textContent=t;$('syncDot').className='dot'+(c?' '+c:'')}
function setPrivateStatus(t,c=''){$('privateSyncStatus').textContent=t;$('privateSyncStatus').className='small '+(c||'muted')}
async function sync(){let u=localStorage.getItem(KFEED)||DEFAULT_FEED;if(!localStorage.getItem(KFEED))localStorage.setItem(KFEED,u);try{setSync('Syncing…');let r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error();market=applyFeed(await r.text());localStorage.setItem(KMARKET,JSON.stringify(market));render();setSync('Latest data synced','ok')}catch(e){setSync('Using cached data · sync failed','err')}}
function migrateV2(){if(localStorage.getItem(KTX))return;let old=localStorage.getItem('quantPrivateTransactionsV2');if(old){localStorage.setItem(KTX,old);let p=localStorage.getItem('quantPrivatePricesV2');if(p)localStorage.setItem(KPRICE,p)}}
function load(){migrateV2();try{txs=JSON.parse(localStorage.getItem(KTX)||'[]')}catch{}try{manualPrices=JSON.parse(localStorage.getItem(KPRICE)||'{}')}catch{}try{let c=JSON.parse(localStorage.getItem(KMARKET)||'null');if(c)market=c}catch{}}
function save(){localStorage.setItem(KTX,JSON.stringify(txs));localStorage.setItem(KPRICE,JSON.stringify(manualPrices))}
const nq=t=>(Number(t.quantity)||0)*(t.unit==='lot'?100:1);
function mprice(i){let k=i.toUpperCase();if(num(manualPrices[k])!==null)return Number(manualPrices[k]);let pp=privatePositions.find(x=>String(x.instrument).toUpperCase()===k);if(pp&&pp.currentPrice!==null&&pp.currentPrice!==undefined&&String(pp.currentPrice).trim()!==''&&num(pp.currentPrice)!==null)return Number(pp.currentPrice);let s=(market.signals||[]).find(x=>String(x.instrument).toUpperCase()===k);return s&&num(s.current)!==null?Number(s.current):null}
function positions(){let B={};[...txs].sort((a,b)=>(String(a.date)+String(a.createdAt||'')).localeCompare(String(b.date)+String(b.createdAt||''))).forEach(t=>{let k=t.instrument.toUpperCase(),p=B[k]||(B[k]={instrument:k,qty:0,avg:0,realized:0,sources:new Set(),links:new Set()}),q=nq(t),pr=Number(t.price)||0,f=Number(t.fee)||0;p.sources.add(t.source);if(t.linkedSignal)p.links.add(t.linkedSignal);if(t.action==='BUY'){let cost=p.qty*p.avg+q*pr+f;p.qty+=q;p.avg=p.qty?cost/p.qty:0}else{let z=Math.min(q,p.qty);p.realized+=(pr-p.avg)*z-f;p.qty-=z;if(p.qty<=0){p.qty=0;p.avg=0}}});return Object.values(B).filter(p=>p.qty>0||Math.abs(p.realized)>0.01).map(p=>{let c=mprice(p.instrument);return {...p,current:c,unreal:c===null?null:(c-p.avg)*p.qty,unrealPct:c===null||!p.avg?null:(c/p.avg-1)*100,sources:[...p.sources],links:[...p.links]}})}
function sigFor(p){return (market.signals||[]).find(s=>p.links.includes(s.id))||(market.signals||[]).find(s=>String(s.instrument).toUpperCase()===p.instrument)}
function currentRR(s){if(!s||num(s.current)===null||num(s.target)===null||num(s.stop)===null)return null;let risk=Number(s.current)-Number(s.stop),reward=Number(s.target)-Number(s.current);return risk>0?reward/risk:null}
function opportunityFor(s){if(!s)return null;let d=(market.decisions||{})[s.id];if(d&&d.label)return d;let c=num(s.current),lo=num(s.entryLow),hi=num(s.entryHigh);if(c!==null&&lo!==null&&hi!==null&&c>=lo&&c<=hi)return {label:'BUY ZONE — thesis intact',reason:'Current price remains inside the original locked entry zone.',currentRR:currentRR(s)};if(c!==null&&lo!==null&&c<lo)return {label:'REVIEW BELOW ENTRY ZONE',reason:'Price is below the original entry zone; cheaper is not automatically better. Re-check why it fell.',currentRR:currentRR(s)};return {label:'HOLD / WAIT',reason:'No new entry instruction in the current feed.',currentRR:currentRR(s)}}
function actualAction(p,s){let cloud=privatePositions.find(x=>String(x.instrument).toUpperCase()===p.instrument);if(cloud&&cloud.aiAction)return {label:cloud.aiAction,reason:cloud.aiReason||'Latest private-portfolio review from the daily AI run.',source:'AI review'};if(!s)return {label:'NOT YET AI-REVIEWED',reason:'No linked/active paper signal. Daily AI review will evaluate this after private sync is connected.',source:'mechanical fallback'};if(p.current!==null&&num(s.stop)!==null&&p.current<=Number(s.stop))return {label:'REVIEW / EXIT ZONE',reason:'Current price has reached or crossed the paper invalidation level.',source:'mechanical fallback'};return {label:'HOLD / FOLLOW THESIS',reason:'Signal remains active; do not cut or average down solely because of a small price move.',source:'mechanical fallback'}}
function render(){
 $('meta').textContent=`${market.meta.version||'Quant'} · Day ${market.meta.day||'?'} · ${market.meta.date||''}`;$('updated').textContent='Updated: '+(market.meta.updatedAt||'—');$('regime').textContent=market.regime.label||'—';$('risk').textContent=market.regime.risk||'—';$('takeaway').textContent=market.regime.takeaway||'';$('macrochips').innerHTML=(market.regime.chips||[]).map(x=>`<div class="kpi"><div class="label">${esc(x.label)}</div><div class="medium">${esc(x.value)}</div></div>`).join('');
 let s=(market.signals||[]).find(x=>String(x.status).toUpperCase()==='OPEN')||(market.signals||[])[0];let o=opportunityFor(s),pr=s&&num(s.current)!==null&&num(s.entry)!==null?(Number(s.current)/Number(s.entry)-1)*100:null,rr=o&&num(o.currentRR)!==null?Number(o.currentRR):currentRR(s);
 $('hero').innerHTML=s?`<div class="card signal"><div class="row wrap"><div><div class="label">LOCKED PAPER SIGNAL</div><div class="big">${esc(s.instrument)} <span class="badge green">${esc(s.action||'')}</span></div></div><div><div class="label">REFERENCE ENTRY</div><div class="big">${money(s.entry)}</div></div></div><div class="kpi-grid" style="margin-top:12px"><div class="kpi"><div class="label">ENTRY ZONE</div><div class="medium">${num(s.entryLow)!==null&&num(s.entryHigh)!==null?money(s.entryLow)+'–'+money(s.entryHigh).replace('Rp',''):'—'}</div></div><div class="kpi"><div class="label">CURRENT</div><div class="medium">${money(s.current)}</div></div><div class="kpi"><div class="label">PAPER P/L</div><div class="medium ${pr!==null&&pr<0?'red':'green'}">${pr===null?'—':pct(pr)}</div></div><div class="kpi"><div class="label">CURRENT R/R</div><div class="medium">${rr===null?'—':Number(rr).toFixed(2)+'×'}</div></div></div><hr><div class="decisionbox"><div class="label">TODAY'S OPPORTUNITY</div><div class="medium">${esc(o?.label||'—')}</div><div class="small muted" style="margin-top:5px">${esc(o?.reason||'')}</div></div><div class="small" style="margin-top:12px">Target <b>${money(s.target)}</b> · invalidation <b>${money(s.stop)}</b> · confidence <b>${esc(s.confidence??'—')}%</b></div></div>`:'<div class="card empty">No active signal.</div>';
 let ps=positions();$('portfolioSummary').innerHTML=`<div class="kpi-grid"><div class="kpi"><div class="label">POSITIONS</div><div class="medium">${ps.filter(p=>p.qty>0).length}</div></div><div class="kpi"><div class="label">TRANSACTIONS</div><div class="medium">${txs.length}</div></div><div class="kpi"><div class="label">UNREALIZED P/L</div><div class="medium">${ps.some(p=>p.unreal!==null)?money(ps.reduce((a,p)=>a+(p.unreal||0),0)):'—'}</div></div><div class="kpi"><div class="label">REALIZED P/L</div><div class="medium">${money(ps.reduce((a,p)=>a+p.realized,0))}</div></div></div>`;
 $('positionList').innerHTML=ps.length?ps.map(p=>{let ss=sigFor(p),a=actualAction(p,ss),cls=a.label.includes('EXIT')||a.label.includes('REDUCE')?'red':a.label.includes('ADD')?'green':a.label.includes('HOLD')?'green':'amber';return `<div class="card position"><div class="row wrap"><div><div class="big">${esc(p.instrument)}</div><div class="small muted">${p.qty.toLocaleString('id-ID')} shares · avg ${money(p.avg)}</div></div><span class="badge ${cls}">${esc(a.label)}</span></div><div class="price-line"><div><div class="label">CURRENT</div><div class="value">${money(p.current)}</div></div><div><div class="label">UNREALIZED</div><div class="value ${p.unrealPct!==null&&p.unrealPct<0?'red':'green'}">${p.unrealPct===null?'—':pct(p.unrealPct)}</div></div><div><div class="label">REALIZED</div><div class="value">${money(p.realized)}</div></div><div><div class="label">ACTION SOURCE</div><div class="value small">${esc(a.source)}</div></div></div>${ss?`<hr><div class="small">AI target <b>${money(ss.target)}</b> · invalidation <b>${money(ss.stop)}</b> · paper entry <b>${money(ss.entry)}</b></div>`:''}<div class="small muted" style="margin-top:8px">${esc(a.reason)}</div><div class="actions" style="margin-top:10px"><button class="btn setprice" data-i="${esc(p.instrument)}">Set current price</button></div></div>`}).join(''):'<div class="card empty">Belum ada transaksi real. Tap + Transaction.</div>';
 document.querySelectorAll('.setprice').forEach(b=>b.onclick=()=>{let x=prompt('Current price '+b.dataset.i,mprice(b.dataset.i)??'');if(x===null)return;let n=Number(x);if(!Number.isFinite(n)||n<=0)return alert('Harga tidak valid');manualPrices[b.dataset.i]=n;save();render()});
 $('watchcards').innerHTML=(market.watchlist||[]).map(w=>`<div class="card wait"><div class="row"><div class="medium">${esc(w.instrument)}</div><span class="badge amber">WAIT</span></div><div class="small muted" style="margin-top:8px">Reference ${esc(w.reference||'—')}</div><div style="margin-top:10px"><div class="label">TRIGGER</div><div class="medium">${esc(w.trigger||'—')}</div></div>${w.note?`<div class="small muted" style="margin-top:8px">${esc(w.note)}</div>`:''}</div>`).join('');
 let sc=market.scorecard||{};$('scoregrid').innerHTML=[['Active',sc.active],['Wait',sc.wait],['Closed',sc.closed],['Win Rate',sc.winRate==null?'N/A':sc.winRate+'%'],['Paper Return',pct(sc.paperReturn)],['Expectancy',sc.expectancy==null?'N/A':pct(sc.expectancy)],['Max Drawdown',sc.maxDrawdown==null?'N/A':pct(sc.maxDrawdown)],['Profit Factor',sc.profitFactor==null?'N/A':sc.profitFactor]].map(x=>`<div class="kpi"><div class="label">${x[0]}</div><div class="medium">${x[1]??'N/A'}</div></div>`).join('');
 $('historyList').innerHTML=(market.history||[]).map(h=>`<div class="timeline-item"><div class="label">${esc(h.date)}</div><div>${esc(h.text)}</div></div>`).join('')||'<div class="empty">No paper history.</div>';
 $('txRows').innerHTML=[...txs].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(t=>`<tr><td>${esc(t.date)}</td><td><b>${esc(t.instrument)}</b></td><td>${esc(t.action)}</td><td>${money(t.price)}</td><td>${esc(t.quantity)} ${esc(t.unit)}</td><td>${esc(t.source)}</td><td>${esc(t.linkedSignal||'—')}</td><td><div class="actions compact"><button class="btn tiny edittx" data-id="${esc(t.id)}">Edit</button><button class="btn tiny danger deltx" data-id="${esc(t.id)}">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="8">No private transactions.</td></tr>';
 document.querySelectorAll('.edittx').forEach(b=>b.onclick=()=>openTx(b.dataset.id));document.querySelectorAll('.deltx').forEach(b=>b.onclick=()=>deleteTx(b.dataset.id));
}
function show(n){document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===n));document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===n));window.scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav));document.querySelectorAll('[data-more]').forEach(b=>b.onclick=()=>show(b.dataset.more));
function openTx(id=''){let t=id?txs.find(x=>x.id===id):null;$('txId').value=t?.id||'';$('txModalTitle').textContent=t?'Edit Transaction':'Add Transaction';$('txSubmit').textContent=t?'Save changes':'Save transaction';$('txDate').value=t?.date||new Date().toISOString().slice(0,10);$('txInstrument').value=t?.instrument||'';$('txAction').value=t?.action||'BUY';$('txPrice').value=t?.price??'';$('txQty').value=t?.quantity??'';$('txUnit').value=t?.unit||'lot';$('txFee').value=t?.fee??0;$('txSource').value=t?.source||'AI Recommendation';$('txLink').value=t?.linkedSignal||'';$('txAccount').value=t?.account||'';$('txNotes').value=t?.notes||'';$('txModal').classList.add('open')}
$('addTx').onclick=()=>openTx();$('closeTx').onclick=()=>$('txModal').classList.remove('open');
async function saveTxFromForm(){let id=$('txId').value||'T-'+Date.now(),existing=txs.find(x=>x.id===id),t={id,date:$('txDate').value,instrument:$('txInstrument').value.trim().toUpperCase(),assetClass:'Equity',action:$('txAction').value,price:Number($('txPrice').value),quantity:Number($('txQty').value),unit:$('txUnit').value,fee:Number($('txFee').value||0),source:$('txSource').value,linkedSignal:$('txLink').value.trim(),account:$('txAccount').value.trim(),notes:$('txNotes').value.trim(),createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(!t.instrument||t.price<=0||t.quantity<=0)return alert('Input tidak valid');let u=localStorage.getItem(KPRIVATEURL),tok=localStorage.getItem(KPRIVTOKEN);if(u&&tok){setPrivateStatus('Saving to private cloud…');try{await privateRequest('upsert',{transaction:t});setPrivateStatus('Private sync connected · transaction saved','green')}catch(e){setPrivateStatus('Private cloud save failed; local copy kept','red')}}let ix=txs.findIndex(x=>x.id===id);ix>=0?txs[ix]=t:txs.push(t);save();$('txModal').classList.remove('open');render();show('portfolio')}
$('txForm').onsubmit=e=>{e.preventDefault();saveTxFromForm()};
async function deleteTx(id){let t=txs.find(x=>x.id===id);if(!t||!confirm(`Delete ${t.instrument} ${t.action} transaction?`))return;let u=localStorage.getItem(KPRIVATEURL),tok=localStorage.getItem(KPRIVTOKEN);if(u&&tok){setPrivateStatus('Deleting from private cloud…');try{await privateRequest('delete',{transactionId:id});setPrivateStatus('Private sync connected · transaction deleted','green')}catch(e){setPrivateStatus('Cloud delete failed; local transaction not deleted','red');return}}txs=txs.filter(x=>x.id!==id);save();render()}
function privateRequest(action,payload={}){return new Promise((resolve,reject)=>{let url=localStorage.getItem(KPRIVATEURL),token=localStorage.getItem(KPRIVTOKEN);if(!url||!token)return reject(Error('Private sync not configured'));let requestId='R-'+Date.now()+'-'+Math.random().toString(16).slice(2),form=document.createElement('form');form.method='POST';form.action=url;form.target='privateSyncFrame';form.style.display='none';let data={action,token,requestId,payload:JSON.stringify(payload)};Object.entries(data).forEach(([k,v])=>{let i=document.createElement('input');i.type='hidden';i.name=k;i.value=v;form.appendChild(i)});document.body.appendChild(form);let timer=setTimeout(()=>{delete pendingPrivate[requestId];form.remove();reject(Error('Private sync timeout'))},15000);pendingPrivate[requestId]={resolve:x=>{clearTimeout(timer);form.remove();resolve(x)},reject:e=>{clearTimeout(timer);form.remove();reject(e)}};form.submit()})}
window.addEventListener('message',e=>{let d=e.data;if(!d||d.source!=='ai-quant-private-sync'||!d.requestId)return;let p=pendingPrivate[d.requestId];if(!p)return;if(d.ok)p.resolve(d);else p.reject(Error(d.error||'Private sync error'));delete pendingPrivate[d.requestId]});
async function syncPrivate(){let u=localStorage.getItem(KPRIVATEURL),tok=localStorage.getItem(KPRIVTOKEN);if(!u||!tok){setPrivateStatus('Not configured yet','muted');return false}setPrivateStatus('Syncing private portfolio…');try{let r=await privateRequest('list'),remote=Array.isArray(r.transactions)?r.transactions:[],rm=new Map(remote.map(x=>[x.id,x]));let upload=txs.filter(t=>{let q=rm.get(t.id);if(!q)return true;let lt=Date.parse(t.updatedAt||t.createdAt||0)||0,rt=Date.parse(q.updatedAt||q.createdAt||0)||0;return lt>rt});if(upload.length){setPrivateStatus('Uploading '+upload.length+' local transaction(s)…','amber');for(let t of upload)await privateRequest('upsert',{transaction:t});r=await privateRequest('list');remote=Array.isArray(r.transactions)?r.transactions:[]}txs=remote;save();privatePositions=Array.isArray(r.positions)?r.positions:[];render();setPrivateStatus('Private sync connected · '+txs.length+' transactions','green');return true}catch(e){setPrivateStatus('Private sync failed: '+e.message,'red');return false}}
$('feedUrl').value=localStorage.getItem(KFEED)||DEFAULT_FEED;$('saveFeed').onclick=async()=>{let u=$('feedUrl').value.trim();if(!u)return $('settingsStatus').textContent='Paste CSV feed URL dulu.';localStorage.setItem(KFEED,u);$('settingsStatus').textContent='Public feed saved.';await sync()};$('syncNow').onclick=sync;
$('privateUrl').value=localStorage.getItem(KPRIVATEURL)||'';$('privateToken').value=localStorage.getItem(KPRIVTOKEN)||'';
function getPrivateToken(){return $('privateToken').value.trim()||localStorage.getItem(KPRIVTOKEN)||''}
function requirePrivateToken(){let t=getPrivateToken();if(!t){setPrivateStatus('Generate a private token first.','red');return null}return t}
async function copyPrivateToken(){let t=requirePrivateToken();if(!t)return false;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(t)}else throw Error('clipboard unavailable');setPrivateStatus('Token copied. Paste it into Apps Script Script Properties as AI_QUANT_TOKEN.','green');return true}catch(e){try{let ta=document.createElement('textarea');ta.value=t;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();ta.setSelectionRange(0,ta.value.length);let ok=document.execCommand('copy');ta.remove();if(!ok)throw Error('copy failed');setPrivateStatus('Token copied with fallback clipboard.','green');return true}catch(e2){setPrivateStatus('Copy is blocked on this phone. Use Show QR or Download token.txt instead.','amber');return false}}}
function downloadPrivateToken(){let t=requirePrivateToken();if(!t)return;let blob=new Blob([t+'\n'],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='AI_Quant_Private_Token.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1200);setPrivateStatus('token.txt downloaded. Transfer it to desktop, then delete the file after setup.','amber')}
function showPrivateTokenQr(){let t=requirePrivateToken();if(!t)return;try{AIQuantQR.render($('tokenQr'),t,8,4);$('qrModal').classList.add('open');setPrivateStatus('Local QR ready. It was generated entirely on this device.','green')}catch(e){setPrivateStatus('Could not generate QR: '+e.message,'red')}}
$('generateToken').onclick=()=>{let a=new Uint8Array(32);crypto.getRandomValues(a);let t=[...a].map(x=>x.toString(16).padStart(2,'0')).join('');$('privateToken').value=t;localStorage.setItem(KPRIVTOKEN,t);setPrivateStatus('New 256-bit token generated. Use Copy token, Show QR, or Download token.txt.','amber')};
$('copyToken').onclick=copyPrivateToken;$('showTokenQr').onclick=showPrivateTokenQr;$('downloadToken').onclick=downloadPrivateToken;$('closeQr').onclick=()=>{$('qrModal').classList.remove('open');$('tokenQr').innerHTML=''};
$('savePrivate').onclick=async()=>{let u=$('privateUrl').value.trim(),t=$('privateToken').value.trim();if(!u||!t)return setPrivateStatus('Endpoint URL and token are both required.','red');localStorage.setItem(KPRIVATEURL,u);localStorage.setItem(KPRIVTOKEN,t);await syncPrivate()};$('privateSyncNow').onclick=syncPrivate;
$('exportTx').onclick=()=>{let blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),transactions:txs,manualPrices},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='AI_Quant_Private_Portfolio_Backup.json';a.click()};$('importTx').onchange=async e=>{let f=e.target.files?.[0];if(!f)return;try{let d=JSON.parse(await f.text());txs=d.transactions||[];manualPrices=d.manualPrices||{};save();render();$('settingsStatus').textContent='Imported locally. Use Private Sync to upload each transaction if needed.'}catch{$('settingsStatus').textContent='Invalid backup.'}};$('checkUpdate').onclick=async()=>{let r=await navigator.serviceWorker?.getRegistration();if(r){await r.update();$('settingsStatus').textContent='Update checked. Close and reopen app.'}};$('clearPrivate').onclick=()=>{if(confirm('Delete all LOCAL private transactions on this phone? Cloud data is not deleted.')){txs=[];manualPrices={};save();render()}};
load();if(!localStorage.getItem(KFEED))localStorage.setItem(KFEED,DEFAULT_FEED);render();sync();syncPrivate();
